INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (1, 'Efetuo Login');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (2, 'Alterou Foto');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (3, 'Desativado');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (4, 'Deletado');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (5, 'Reativado');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (6, 'Alterou Senha');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (7, 'Alterou Email');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (8, 'Alterou Nome de Perfil');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (9, 'Comentou');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (10, 'Cadastro No Site');
INSERT INTO multiplayer4.ACOES_LOG (`COD_ACOES_LOG`, `NOME_ACAO`) 
	VALUES (11, 'Efetuo Logout');
	
INSERT INTO multiplayer4.TIPO (`COD_TIPO`, `TIPO_USUARIO`) 
	VALUES (1, 'ADM');
INSERT INTO multiplayer4.TIPO (`COD_TIPO`, `TIPO_USUARIO`) 
	VALUES (2, 'RES');
INSERT INTO multiplayer4.TIPO (`COD_TIPO`, `TIPO_USUARIO`) 
	VALUES (3, 'COL');
INSERT INTO multiplayer4.TIPO (`COD_TIPO`, `TIPO_USUARIO`) 
	VALUES (4, 'DES');

INSERT INTO multiplayer4.USUARIO (`NOME_USUARIO`, `EMAIL_USUARIO`, `SENHA_USUARIO`, `TIPO_USUARIO`, `DATA_NASCIMENTO`, `USUARIO_DESATIVADO`) 
	VALUES ('Administrador', 'admin@admin.com', 'admin', 1, '2014-08-12', NULL);
	
INSERT INTO multiplayer4.CATEGORIA (`COD_CATEGORIA`, `NOME_CATEGORIA`) 
	VALUES (1, 'ps3');
INSERT INTO multiplayer4.CATEGORIA (`COD_CATEGORIA`, `NOME_CATEGORIA`) 
	VALUES (2, 'ps4');
INSERT INTO multiplayer4.CATEGORIA (`COD_CATEGORIA`, `NOME_CATEGORIA`) 
	VALUES (3, 'wii');
INSERT INTO multiplayer4.CATEGORIA (`COD_CATEGORIA`, `NOME_CATEGORIA`) 
	VALUES (4, 'wii_u');
INSERT INTO multiplayer4.CATEGORIA (`COD_CATEGORIA`, `NOME_CATEGORIA`) 
	VALUES (5, '3ds');
INSERT INTO multiplayer4.CATEGORIA (`COD_CATEGORIA`, `NOME_CATEGORIA`) 
	VALUES (6, 'xbox_360');
INSERT INTO multiplayer4.CATEGORIA (`COD_CATEGORIA`, `NOME_CATEGORIA`) 
	VALUES (7, 'xbox_one');
INSERT INTO multiplayer4.CATEGORIA (`COD_CATEGORIA`, `NOME_CATEGORIA`) 
	VALUES (8, 'pc');
	

	
